In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys

In [6]:
a = np.array([1,3,5])
b = np.array([1,2,3])

a*b

array([ 1,  6, 15])

In [22]:
b = np.array([[2.6,8.9,3.4],[5.7,2.9,6.8]])
print(b)
b[1:3]

[[2.6 8.9 3.4]
 [5.7 2.9 6.8]]


array([[5.7, 2.9, 6.8]])